//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace JonathanRobbins.MicrositeKit.WebApp.Layouts.Sublayouts.Components {
    
    
    public partial class CollectionPanel {
        
        /// <summary>
        /// cpvFeaturedItem control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::JonathanRobbins.MicrositeKit.WebApp.Layouts.Sublayouts.Components.CollectionPanelView cpvFeaturedItem;
        
        /// <summary>
        /// lvMediumCollection control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.ListView lvMediumCollection;
        
        /// <summary>
        /// lvSmallCollection control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.ListView lvSmallCollection;
        
        /// <summary>
        /// lvHiddenSmall control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.ListView lvHiddenSmall;
        
        /// <summary>
        /// sctSeeMore control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Sitecore.Web.UI.WebControls.Text sctSeeMore;
    }
}
